# Generated by Django 3.2.13 on 2022-06-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('response', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=6, max_digits=15)),
                ('created_at', models.DateTimeField(max_length=255)),
                ('updated_at', models.DateTimeField(max_length=255)),
                ('assessment_id', models.IntegerField()),
                ('recommendations', models.TextField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=15)),
                ('section_id', models.IntegerField()),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
