# Generated by Django 3.2.13 on 2022-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220607_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_first_name', models.CharField(max_length=255)),
                ('customer_last_name', models.CharField(max_length=255)),
                ('personal_id', models.CharField(max_length=255)),
                ('customer_age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=15)),
                ('loan_purpose', models.IntegerField()),
                ('loan_section', models.IntegerField()),
                ('status', models.IntegerField()),
                ('total_score', models.DecimalField(decimal_places=6, max_digits=15)),
                ('region_name', models.CharField(max_length=255)),
                ('score_ratio', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='Loan_purposes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_purposes',
            },
        ),
        migrations.CreateModel(
            name='Loan_section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('importance_value', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                'db_table': 'loan_section',
            },
        ),
        migrations.CreateModel(
            name='Question_category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question_category',
            },
        ),
        migrations.CreateModel(
            name='Question_groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question_groups',
            },
        ),
        migrations.CreateModel(
            name='Question_types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=512)),
                ('questions', models.CharField(max_length=1028)),
                ('scores', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('section', models.IntegerField()),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('has_recommendations', models.IntegerField()),
                ('group', models.IntegerField()),
                ('category', models.IntegerField()),
                ('order', models.IntegerField()),
                ('recommendation_by_score', models.CharField(max_length=1028)),
                ('recommendation_score', models.DecimalField(decimal_places=6, max_digits=15)),
                ('related', models.IntegerField()),
                ('trigger_related_val', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assessment_id', models.IntegerField()),
                ('answers', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=255)),
                ('scenario_description', models.TextField()),
                ('risk_exposure_value', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_names', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
